### ISSUE TITLE
The license of an external package is not included

### ISSUE THREAD

**Issue by scola84** [mjeanroy/rollup-plugin-license#440]
If I add a package to `external` in the global rollup.config.js the license of that package is not included. Is that on purpose, in the spirit of [Should you care about the license?](https://medium.com/@vovabilonenko/licenses-of-npm-dependencies-bacaa00c8c65)?

**Comment by mjeanroy** [comment]
Hi @scola84,
Currently, if the package is not included in the bundle, than the dependency will not appear in the dependency report. I'm not sure if it should be a bug or not, I'll see if I can add an option to enable this or not.

Sorry for the delay, I had a lot of work ;)

**Comment by scola84** [comment]
Thanks! I wouldn't file it as a bug, but adding an option would be nice, so that it is possible to follow different legal models.

**Comment by mjeanroy** [comment]
@scola84 I tried to fix this issue, but it is not so easy. The problem here is that an external is not loaded by rollup, so we have no way to find the dependency on disk (and so read the associated `package.json`). In fact, this kind of dependency may not be declared in `package.json` at all.

I'm not sure if it is really a problem to ignore these dependencies, since these will not be included in the final bundle at all (what is called in the article you mentioned "dynamic linking"), so, for me, it makes sense to not include these in the third party output.

For now, I won't be able to fix it, unless we can think about a workaround?

**Comment by scola84** [comment]
> so, for me, it makes sense to not include these in the third party output

I completely agree with your conclusion, so I'll close this issue.
