### ISSUE TITLE
Problem with Stencil license

### ISSUE THREAD

**Issue by Jagget** [mjeanroy/rollup-plugin-license#553]
I created bug there, but now decided to ask here, if it is fixable from this side? 

https://github.com/ionic-team/stencil/issues/2391

**Comment by mjeanroy** [comment]
@Jagget Not sure to understand the issue exactly, I don't know how stencil works and define its dependencies. Do you have a reproducible test case?

**Comment by Jagget** [comment]
@mjeanroy  https://github.com/Jagget/stencil-bug-2

**Comment by mjeanroy** [comment]
@Jagget I fixed it by checking that the package name is valid (not the case with stencil internal packages). A non valid package should probably used only internally, so in my opinion it is a good idea to check for a valid `package.json` upper in the directory tree (except if it defines a license field, otherwise it will be used).

Is that possible for you to check on master before I release a new version?

**Comment by Jagget** [comment]
Thank you! It is fixed!

For the future: is there some general solution to map wrongly detected licenses and point them to the right files?

**Comment by mjeanroy** [comment]
> For the future: is there some general solution to map wrongly detected licenses and point them to the right files?

That is something I have in mind since the beginning, but to be honest I would like to avoid it as long as I can. I prefer to fix all the "edge case" before adding complexity in the configuration.

**Comment by mjeanroy** [comment]
@Jagget Version 2.1.0 and 1.1.0 have been published with the fix.
